import time
import keyboard
import random

tokenlist = ["O" , "z" , "Q" , "W" , "A" , "x" , "0" , "l" , "M" ,  "L" , "s" , "l" , "w" , "q" , "n" , "pw" , "p" , "l" , "w" , "q" , "w" , "S" , "w" , "c" , "h" , "j" , "a" , "1" , "r" , "y" , "2" , "s" , "zz" , "7" , "5" , "p" , "Q" , "w" , "Z" , "k" , "l" , "mn" , "lw" , "wz" , "zz" , "wT" , "rT" , "Tw" , "wZ" , "I" , "i" , "u" , "F" , "f" , "w"]
tokenbaslangicc = ["OTcwM"]

tokenbaslangic = random.choice(tokenbaslangicc)
token1 = random.choice(tokenlist)
token2 = random.choice(tokenlist)
token3 = random.choice(tokenlist)
token4 = random.choice(tokenlist)
token5 = random.choice(tokenlist)
token6 = random.choice(tokenlist)
token7 = random.choice(tokenlist)
token8 = random.choice(tokenlist)
token9 = random.choice(tokenlist)
token10 = random.choice(tokenlist)
token11 = random.choice(tokenlist)
token12 = random.choice(tokenlist)
token13 = random.choice(tokenlist)
token14 = random.choice(tokenlist)
token15 = random.choice(tokenlist)
token16 = random.choice(tokenlist)
token17 = random.choice(tokenlist)
token18 = random.choice(tokenlist)
token19 = random.choice(tokenlist)
token20 = random.choice(tokenlist)
token21 = random.choice(tokenlist)
token22 = random.choice(tokenlist)
token23 = random.choice(tokenlist)
token24 = random.choice(tokenlist)
token25 = random.choice(tokenlist)
token26 = random.choice(tokenlist)
token27 = random.choice(tokenlist)
token28 = random.choice(tokenlist)
token29 = random.choice(tokenlist)
token30 = random.choice(tokenlist)
token31 = random.choice(tokenlist)
token32 = random.choice(tokenlist)
token33 = random.choice(tokenlist)
token34 = random.choice(tokenlist)
token35 = random.choice(tokenlist)
token36 = random.choice(tokenlist)
token37 = random.choice(tokenlist)
token38 = random.choice(tokenlist)
token39 = random.choice(tokenlist)
token49 = random.choice(tokenlist)
token40 = random.choice(tokenlist)
token41 = random.choice(tokenlist)
token42 = random.choice(tokenlist)
token43 = random.choice(tokenlist)
token44 = random.choice(tokenlist)
token45 = random.choice(tokenlist)
token46 = random.choice(tokenlist)
token47 = random.choice(tokenlist)
token48 = random.choice(tokenlist)
token49 = random.choice(tokenlist)
token50 = random.choice(tokenlist)
token51 = random.choice(tokenlist)
token52 = random.choice(tokenlist)
token53 = random.choice(tokenlist)
token54 = random.choice(tokenlist)
token55 = random.choice(tokenlist)
print("Program Lorex tarafindan yapilmistir!")
print("")
print("")
print("")
print("Fake Token Olusturuldu!")
print(tokenbaslangic+token1+token2+token3+token4+token5+token6+token7+token8+token9+token10+token11+token12+token13+token14+token15+token16+token17+token18+token19+token20+token21+token22+token23+token24+token25+token26+token27+token28+token29+token30+token31+token32+token33+token34+token35+token36+token37+token38+token39+token40+token41+token42+token43+token44+token45+token46+token47+token48+token49+token50+token51+token52+token53+token54+token55)

time.sleep(999)
